return {
  {
    title = "General",
    abbr = "Gen",
    items = {
      { keys = "jj",   desc = "Escape insert mode" },
      { keys = ",,",   desc = "Toggle this cheatsheet" },
      { keys = ",q",   desc = "Close current split" },
      { keys = ",cr",  desc = "Reload vimrc" },
      { keys = ",c.",  desc = "Open vimrc in current buffer" },
    },
  },
  {
    title = "Splits & tabs",
    abbr = "Splt",
    items = {
      { keys = ",v / ,s",      desc = "Split vertical / horizontal" },
      { keys = ",tn",          desc = "New tab" },
      { keys = ",t1 .. ,t9",   desc = "Switch to tab 1..9" },
      { keys = ",t0",          desc = "Switch to last tab" },
      { keys = ",m{w,a,s,d}",  desc = "Window nav (up/left/down/right)" },
    },
  },
  {
    title = "Buffers",
    abbr = "Bufs",
    items = {
      { keys = ",1 .. ,9",  desc = "Switch to visible buffer 1..9" },
      { keys = ",0",        desc = "Switch to visible buffer 10" },
      { keys = ",bd",       desc = "Delete current buffer (mini.bufremove)" },
      { note = "Buffers scoped per tab (scope.nvim); bufferline shows this tab's buffers only." },
    },
  },
  {
    title = "Workspaces",
    abbr = "Wksp",
    items = {
      { note = "A workspace is a named tab page with a persisted snapshot of its open files and terminals." },
      { keys = ",Ws",  desc = "Save current tab as workspace" },
      { keys = ",Ww",  desc = "Switch open workspaces (picker)" },
      { keys = ",Wo",  desc = "Saved workspaces picker (open from disk)" },
      { note = "    <CR> open  ·  <C-r> rename  ·  <C-d> delete highlighted" },
      { keys = ",Wx",  desc = "Close current tab (saved copy stays on disk)" },
      { note = "Floating prompts: jj → normal mode · <CR> confirm · <Esc>/<C-c> cancel" },
    },
  },
  {
    title = "Files & search",
    abbr = "Find",
    items = {
      { keys = ",ff",  desc = "Find files" },
      { keys = ",fg",  desc = "Find git files" },
      { keys = ",fl",  desc = "Live grep (ripgrep)" },
      { keys = ",fe",  desc = "Live grep open buffers" },
      { keys = ",fs",  desc = "Search buffers" },
      { keys = ",fw",  desc = "Search projects" },
      { keys = ",fv",  desc = "Search terminals" },
    },
  },
  {
    title = "File explorer",
    abbr = "Tree",
    items = {
      { keys = ",<space>",  desc = "Focus tree" },
      { keys = ",e",        desc = "Toggle tree (show/hide)" },
      { keys = ",w",        desc = "Reveal current file in tree" },
    },
  },
  {
    title = "Oil.nvim",
    abbr = "Oil",
    items = {
      { keys = "-",  desc = "Open parent directory as oil buffer" },
      { note = "Edit listing like text: rename=edit name, delete=delete line," },
      { note = "  move=cut/paste between oil buffers. :w applies. - goes up." },
    },
  },
  {
    title = "Flash (jump)",
    abbr = "Jump",
    items = {
      { keys = "s + chars",  desc = "Jump to any on-screen position" },
      { keys = "S",          desc = "Jump to treesitter node" },
      { note = "`s` overrides substitute-char; use `cl` instead." },
    },
  },
  {
    title = "Terminal",
    abbr = "Term",
    items = {
      { keys = ",rh",         desc = "Open terminal horizontal split" },
      { keys = ",rv",         desc = "Open terminal vertical split" },
      { keys = ",rt",         desc = "Open terminal in new tab" },
      { keys = ",rc",         desc = "Open terminal in current window" },
      { keys = ",rn",         desc = "Rename current terminal" },
      { keys = "<Esc><Esc>",  desc = "Exit terminal mode" },
      { note = "Terminals appear in bufferline; reach via ,1..,9 like any buffer." },
    },
  },
  {
    title = "Editing",
    abbr = "Edit",
    items = {
      { keys = "yc{motion}",   desc = "Yank to system clipboard" },
      { keys = "ga{motion}",   desc = "EasyAlign (e.g. gaip2= aligns at 2nd =)" },
      { keys = "gS / gJ",      desc = "Split / join line" },
      { keys = "gcc",          desc = "Toggle line comment" },
      { keys = "gc{motion}",   desc = "Comment region (e.g. gcip = paragraph)" },
      { keys = "gc (visual)",  desc = "Comment selection" },
      { keys = "Alt+h/j/k/l",  desc = "Move line / visual selection" },
    },
  },
  {
    title = "Surround",
    abbr = "Srnd",
    items = {
      { note = "Opening bracket adds spaces, closing doesn't:" },
      { note = "  ysiw( → ( word )   ysiw) → (word)" },
      { note = "Add:" },
      { keys = "ysiw)",          desc = "Surround word with ()" },
      { keys = "ys$)",           desc = "Surround to end of line" },
      { keys = "yss)",           desc = "Surround entire line" },
      { keys = "yS{motion}{c}",  desc = "Surround on new lines" },
      { keys = "S) (visual)",    desc = "Surround selection" },
      { keys = "C-g s ) (ins)",  desc = "Insert surround at cursor" },
      { note = "Delete:" },
      { keys = "ds(",            desc = "Delete surrounding ()" },
      { keys = "ds] / ds\"",     desc = "Delete surrounding [] / \"\"" },
      { keys = "dst",            desc = "Delete surrounding HTML/XML tag" },
      { note = "Change:" },
      { keys = "cs)\"",          desc = "Change () to \"\"" },
      { keys = "cs\"'",          desc = "Change \"\" to ''" },
      { keys = "cst<div>",       desc = "Change surrounding tag" },
      { note = "Targets: ( [ { < ' \" t (tag) f (function call)" },
    },
  },
  {
    title = "Git",
    abbr = "Git",
    items = {
      { keys = "]c / [c",  desc = "Next / prev changed hunk" },
      { keys = ",gs",      desc = "Stage hunk" },
      { keys = ",gr",      desc = "Reset hunk" },
      { keys = ",gp",      desc = "Preview hunk popup" },
      { keys = ",gb",      desc = "Toggle inline blame" },
      { note = "Full-repo ops: :Git status, :Git blame, etc. (fugitive)" },
    },
  },
  {
    title = "LSP",
    abbr = "LSP",
    items = {
      { keys = "gd",   desc = "Go to definition" },
      { keys = "gD",   desc = "Go to declaration" },
      { keys = "gr",   desc = "List references" },
      { keys = "gi",   desc = "Go to implementation" },
      { keys = "K",    desc = "Hover docs (K again to enter popup)" },
      { keys = ",lr",  desc = "Rename symbol (workspace-wide)" },
      { keys = ",la",  desc = "Code action" },
      { keys = ",lf",  desc = "Format buffer" },
      { note = "Diagnostics inline + virtual-text on by default." },
    },
  },
  {
    title = "Diagnostics",
    abbr = "Diag",
    items = {
      { keys = ",xx",  desc = "Toggle workspace diagnostics" },
      { keys = ",xd",  desc = "Document-only diagnostics" },
      { keys = ",xq",  desc = "Quickfix list in trouble" },
      { keys = ",xl",  desc = "Location list in trouble" },
      { note = "Inside trouble: <CR> jump · q close · ? help" },
    },
  },
  {
    title = "Autocomplete",
    abbr = "Auto",
    items = {
      { keys = "<Tab> / <S-Tab>",  desc = "Cycle completion menu" },
      { keys = "<CR>",             desc = "Confirm selection (only when highlighted)" },
    },
  },
}
